# Generated by Django 5.2.3 on 2025-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validate_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_idea', models.TextField()),
                ('business_domain', models.CharField(choices=[('TECH', 'Technology & Software'), ('HEALTH', 'Healthcare & Medical'), ('EDTECH', 'Education & EdTech'), ('FINTECH', 'Finance & FinTech'), ('ECOM', 'E-commerce & Retail'), ('FOOD', 'Food & Beverage'), ('LOGISTICS', 'Transportation & Logistics'), ('ENV', 'Sustainability & Environment'), ('MEDIA', 'Entertainment & Media'), ('OTHER', 'Other')], max_length=50)),
                ('problem_statement', models.TextField()),
                ('business_goal', models.TextField()),
                ('monetization_strategy', models.TextField()),
                ('social_impact', models.TextField()),
                ('timeline', models.TextField()),
            ],
        ),
    ]
