# Generated by Django 5.2.3 on 2025-07-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_validate_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='validate_form',
            name='feasibility_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validate_form',
            name='feasibility_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validate_form',
            name='feasibility_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validate_form',
            name='monetization_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validate_form',
            name='risk_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validate_form',
            name='risk_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validate_form',
            name='swot_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
